// Seed data for fine rules - Season 25/26
// Generated for bulk import via importFineRulesSeason2526()

export const fineRulesSeason2526 = [
  // Indmeldelse
  {
    category: "Indmeldelse",
    emoji: "📋",
    title: "Indmeldelse til bødekassen anno 25/26",
    amount: 150,
    description: "Obligatorisk indmeldelse til bødekassen for sæsonen",
  },

  // System / Regler
  {
    category: "System",
    emoji: "⚖️",
    title: "Indgå i forhold med ungdomsspiller fra klubben - månedligt gebyr",
    amount: 55,
    description: "Månedsgebyr (kan ikke købes wildcard imod)",
  },
  {
    category: "System",
    emoji: "⚖️",
    title: "Misse klubtjans",
    amount: 150,
    description: "Fx. manglende oprydning eller linjedommer",
  },
  {
    category: "System",
    emoji: "⚖️",
    title: "Komme for sent til oprydning",
    amount: 4,
    description: "4 kr. pr. minut",
  },
  {
    category: "System",
    emoji: "⚖️",
    title: "Manglende indbetaling af bøder",
    amount: 5,
    description: "5 kr. pr. dag",
  },
  {
    category: "System",
    emoji: "⚖️",
    title: "Melde sig ud af bødekassen efter sæson er startet",
    amount: 500,
    description: "Høj pris for sent exit",
  },

  // For sent til træning
  {
    category: "For sent til træning",
    emoji: "⏰",
    title: "For sent til træning - pr. minut",
    amount: 2,
    description: "2 kr. pr. minut. Kan ikke købes wildcard imod",
  },

  // Træning/holdkamp bøder
  {
    category: "Træning/Holdkamp",
    emoji: "👟",
    title: "Ankelsokker til træning",
    amount: 100,
    description: "",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "🧦",
    title: "Anden farve sok end sort og hvid",
    amount: 50,
    description: "",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "🌈",
    title: "Dårlig farvekoordinering",
    amount: 35,
    description: "Bestemt via demokrati i omklæderen (Wittrock special)",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "📱",
    title: "Mobil under træning",
    amount: 50,
    description: "Far-regel",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "📱",
    title: "Mobil under holdkamp",
    amount: 50,
    description: "",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "👕",
    title: "Glemt tøj - låning påkrævet",
    amount: 25,
    description: "Nødt til at låne fra anden person",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "❌",
    title: "Ikke møde op til tilmeldt træning",
    amount: 50,
    description: "",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "🔴",
    title: "Møde op i Solrød trøje",
    amount: 100,
    description: "",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "👥",
    title: "Møde op til træning med samme t-shirt som anden",
    amount: 25,
    description: "",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "🏃",
    title: "Stoppe før tid eller side en runde over",
    amount: 20,
    description: "Far-regel",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "🏐",
    title: "Tabe dyst om hal",
    amount: 35,
    description: "",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "💧",
    title: "Glemt drikkedunk",
    amount: 25,
    description: "",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "🇬🇧",
    title: "Tabe i engelsk inden holdkamp",
    amount: 10,
    description: "",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "📊",
    title: "8 eller derunder i et sæt",
    amount: 30,
    description: "+5 kr. for hvert ekstra point man sutter",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "♻️",
    title: "Glemt at smide tomt boldkasse ud",
    amount: 25,
    description: "",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "🧴",
    title: "Glemt del til træning eller holdkamp",
    amount: 20,
    description: "",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "🥄",
    title: "Ofre en ske",
    amount: 100,
    description: "",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "🥄",
    title: "Låne en ske",
    amount: 50,
    description: "",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "🥄",
    title: "Springe lånt ske",
    amount: 50,
    description: "Plus ny opstrengning",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "🚪",
    title: "Tank top torsdag",
    amount: 35,
    description: "Inden hver holdrunde",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "🗑️",
    title: "Tabe æsken",
    amount: 30,
    description: "",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "⚠️",
    title: "Gult kort",
    amount: 100,
    description: "Søby",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "🔴",
    title: "Rødt kort",
    amount: 300,
    description: "",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "😢",
    title: "Tabe til en spiller fra Solrød",
    amount: 50,
    description: "Buuuuuuuh!",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "🏆",
    title: "Vinde turnering - de 2 første",
    amount: 35,
    description: "Hvis man vinder mere end 2, belønnes det med 35 kr. tilgode",
  },
  {
    category: "Træning/Holdkamp",
    emoji: "⭐",
    title: "Kampens spiller",
    amount: 30,
    description: "",
  },

  // Afbud
  {
    category: "Afbud",
    emoji: "📞",
    title: "Glemt afbud til træning",
    amount: 50,
    description: "Tag jer sammen!",
  },
  {
    category: "Afbud",
    emoji: "⏳",
    title: "For sent afbud (kl. 12-14)",
    amount: 25,
    description: "Afbud efter kl. 14 ses som glemt afbud",
  },
  {
    category: "Afbud",
    emoji: "🛏️",
    title: "Dårligt eller for sent afbud til holdkamp",
    amount: 50,
    description: "1 uge inden",
  },
  {
    category: "Afbud",
    emoji: "🍻",
    title: "Afbud til træning pga. druk",
    amount: 75,
    description: "Oli-regel",
  },

  // Ikke møde op
  {
    category: "Fraværende",
    emoji: "😴",
    title: "Eneste herre på holdet der taber en kamp",
    amount: 40,
    description: "",
  },
  {
    category: "Fraværende",
    emoji: "📅",
    title: "Fraværende til træning i længere tid",
    amount: 50,
    description: "3 uger eller mere",
  },

  // Lidt lækkert
  {
    category: "Lidt lækkert",
    emoji: "🩳",
    title: "Ikke at trække i underbukser først efter bad",
    amount: 75,
    description: "",
  },
  {
    category: "Lidt lækkert",
    emoji: "🍖",
    title: "Kød på bænk",
    amount: 75,
    description: "",
  },
  {
    category: "Lidt lækkert",
    emoji: "🚿",
    title: "Pis i bad",
    amount: 50,
    description: "",
  },
  {
    category: "Lidt lækkert",
    emoji: "🛁",
    title: "Ikke deltage i fællesbad efter tirsdag/torsdag træning",
    amount: 10,
    description: "Strøm-regel",
  },
  {
    category: "Lidt lækkert",
    emoji: "🍆",
    title: "Stiv dolk i badet",
    amount: 250,
    description: "Premium fine",
  },
  {
    category: "Lidt lækkert",
    emoji: "🎯",
    title: "Glemt debut bajer",
    amount: 75,
    description: "",
  },

  // Klubarrangementer
  {
    category: "Klubarrangementer",
    emoji: "🎉",
    title: "Ikke deltage til klubfest uden godkendt årsag",
    amount: 50,
    description: "Skal godkendes af formand eller næstformand",
  },
  {
    category: "Klubarrangementer",
    emoji: "🍜",
    title: "Kaste suppen under eller til klubarrangement",
    amount: 35,
    description: "",
  },
  {
    category: "Klubarrangementer",
    emoji: "🧹",
    title: "Kaste suppen i omklæderen",
    amount: 50,
    description: "Du rydder selv op",
  },
  {
    category: "Klubarrangementer",
    emoji: "📸",
    title: "Mediebøde",
    amount: 20,
    description: "Maks 2 om ugen",
  },
  {
    category: "Klubarrangementer",
    emoji: "🌙",
    title: "Gå død under klubfest eller klubbytur før midnat",
    amount: 50,
    description: "Før kl. 12",
  },
  {
    category: "Klubarrangementer",
    emoji: "👕",
    title: "Glemt klubdel",
    amount: 100,
    description: "",
  },
  {
    category: "Klubarrangementer",
    emoji: "🍹",
    title: "Spilde en andens drink",
    amount: 10,
    description: "",
  },

  // Månedens
  {
    category: "Månedens",
    emoji: "🏅",
    title: "Månedens mindste",
    amount: 25,
    description: "Den med færrest bøder. Kan gives til flere",
  },
  {
    category: "Månedens",
    emoji: "🤪",
    title: "Månedens dummeste",
    amount: 30,
    description: "",
  },
  {
    category: "Månedens",
    emoji: "💭",
    title: "Brokke-bøde",
    amount: 20,
    description: "Vi laver et bødebrokkeråd",
  },
  {
    category: "Månedens",
    emoji: "💰",
    title: "Tilskud til måneds-meldt",
    amount: -40,
    description: "Den der meldt flest bøder får 40 kr. som tilskud - vær nogle svin!",
  },

  // Griss
  {
    category: "Griss",
    emoji: "😏",
    title: "Griss",
    amount: 100,
    description: "",
  },
  {
    category: "Griss",
    emoji: "👶",
    title: "Griss med ungdomsspiller",
    amount: 100,
    description: "Til og med u19 2'års",
  },
  {
    category: "Griss",
    emoji: "😒",
    title: "Griss med spiller fra Solrød",
    amount: 200,
    description: "Buuuuuh!",
  },
  {
    category: "Griss",
    emoji: "👰",
    title: "Griss med pige fra senior truppen",
    amount: 75,
    description: "",
  },
  {
    category: "Griss",
    emoji: "📱",
    title: "Flødebøde",
    amount: 25,
    description: "Fx. kig på Frederiks Solbergs insta",
  },
  {
    category: "Griss",
    emoji: "📣",
    title: "Griss-bøderne offentliggjort",
    amount: 150,
    description: "Hvis det bliver delt",
  },
  {
    category: "Griss",
    emoji: "🚫",
    title: "Cockblock af bødekasse-medlem",
    amount: 75,
    description: "",
  },
  {
    category: "Griss",
    emoji: "💔",
    title: "Utroskab",
    amount: 500,
    description: "Premium fine",
  },

  // Øvrige
  {
    category: "Øvrige",
    emoji: "💩",
    title: "Skide under øvelser på banen",
    amount: 20,
    description: "Bello",
  },
  {
    category: "Øvrige",
    emoji: "⛪",
    title: "Tag til gudstjeneste",
    amount: 50,
    description: "Maks 5 gange om året",
  },
];
